-- language=postgresql

CREATE TABLE IF NOT EXISTS sentences
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sentence_type INT          NOT NULL,
    content       VARCHAR(500) NOT NULL,
    level         INT          NOT NULL,
    create_time   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE sentences IS '句子表，用于存储出题句子';
COMMENT ON COLUMN sentences.id IS '句子ID，主键';
COMMENT ON COLUMN sentences.sentence_type IS '句子类型,1.日常2.职场3.社交';
COMMENT ON COLUMN sentences.content IS '句子内容';
COMMENT ON COLUMN sentences.level IS '句子难度等级（N5~N1）';
COMMENT ON COLUMN sentences.create_time IS '创建时间';

-- DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS users
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username            VARCHAR(100) NOT NULL UNIQUE,
    current_sentence_id BIGINT,
    mode                INT,
    sentence_count      BIGINT    DEFAULT 0,
    create_time         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE users IS '用户表，记录用户学习状态';
COMMENT ON COLUMN users.id IS '用户ID，主键';
COMMENT ON COLUMN users.username IS '用户名，唯一标识';
COMMENT ON COLUMN users.current_sentence_id IS '当前学习中的句子ID';
COMMENT ON COLUMN users.mode IS '模式 1.翻译 2.错题回溯';
COMMENT ON COLUMN users.sentence_count IS '用户的总答题量';
COMMENT ON COLUMN users.create_time IS '用户创建时间';

CREATE INDEX IF NOT EXISTS idx_users_sentence
    ON users (current_sentence_id);
COMMENT ON INDEX idx_users_sentence IS '用户当前句子';


CREATE TABLE IF NOT EXISTS user_answer_record
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT  NOT NULL,
    sentence_id BIGINT  NOT NULL,
    correct     BOOLEAN NOT NULL,
    create_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE user_answer_record IS '用户错句关联表，记录用户在句子上的错误情况';
COMMENT ON COLUMN user_answer_record.id IS '主键ID';
COMMENT ON COLUMN user_answer_record.user_id IS '用户ID';
COMMENT ON COLUMN user_answer_record.sentence_id IS '句子ID';
COMMENT ON COLUMN user_answer_record.correct IS '是否正确';
COMMENT ON COLUMN user_answer_record.create_time IS '记录创建时间';

CREATE INDEX IF NOT EXISTS idx_user_sentence
    ON user_answer_record (user_id, sentence_id);
COMMENT ON INDEX idx_user_sentence IS '用户和句子ID';