-- language=H2

CREATE TABLE IF NOT EXISTS sentences
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sentence_type VARCHAR(500) NOT NULL,
    content       TEXT         NOT NULL,
    level         INT          NOT NULL,
    create_time   TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE sentences IS '句子表，用于存储出题句子';
COMMENT ON COLUMN sentences.id IS '句子ID，主键';
COMMENT ON COLUMN sentences.sentence_type IS '句子类型（如：日常/职场/社交）';
COMMENT ON COLUMN sentences.content IS '句子内容';
COMMENT ON COLUMN sentences.level IS '句子难度等级（N5~N1）';
COMMENT ON COLUMN sentences.create_time IS '创建时间';

CREATE TABLE IF NOT EXISTS users
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username            VARCHAR(100) NOT NULL UNIQUE,
    current_sentence_id BIGINT,
    sentence_count      BIGINT    DEFAULT 0,
    create_time         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
COMMENT ON TABLE users IS '用户表，记录用户学习状态';
COMMENT ON COLUMN users.id IS '用户ID，主键';
COMMENT ON COLUMN users.username IS '用户名，唯一标识';
COMMENT ON COLUMN users.current_sentence_id IS '当前学习中的句子ID';
COMMENT ON COLUMN users.sentence_count IS '用户的总答题量';
COMMENT ON COLUMN users.create_time IS '用户创建时间';

CREATE INDEX IF NOT EXISTS idx_users_sentence
    ON users (current_sentence_id);
COMMENT ON INDEX idx_users_sentence IS '用户当前句子';


CREATE TABLE IF NOT EXISTS user_sentence_errors
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id         BIGINT NOT NULL,
    sentence_id     BIGINT NOT NULL,
    wrong_count     INT    NOT NULL DEFAULT 0,
    last_wrong_time TIMESTAMP,
    create_time     TIMESTAMP       DEFAULT CURRENT_TIMESTAMP,
);
COMMENT ON TABLE user_sentence_errors IS '用户错句关联表，记录用户在句子上的错误情况';
COMMENT ON COLUMN user_sentence_errors.id IS '主键ID';
COMMENT ON COLUMN user_sentence_errors.user_id IS '用户ID';
COMMENT ON COLUMN user_sentence_errors.sentence_id IS '句子ID';
COMMENT ON COLUMN user_sentence_errors.wrong_count IS '改句子累计错误次数';
COMMENT ON COLUMN user_sentence_errors.last_wrong_time IS '最近一次答错时间';
COMMENT ON COLUMN user_sentence_errors.create_time IS '记录创建时间';

