package com.recall.dto.resp;

import lombok.Getter;
import lombok.Setter;
import lombok.extern.slf4j.Slf4j;

import java.util.regex.Matcher;
import java.util.regex.Pattern;

/**
 * Helper class to accumulate text chunks from an LLM stream and parse them into an EvaluationResult.
 */
@Getter
@Slf4j
public class LlmAccumulator {
    /** Buffer to accumulate the full text content from the stream. */
    private final StringBuilder content = new StringBuilder();
    /** Indicates whether the user's answer was correct. */
    private Boolean correct;

    /** The answer generated by the model. */
    private String cleanedAnswer;

    /** The final metadata frame from the stream. */
    private OllamaChatResponse finalMetadata = null;

    /**
     * Appends a text chunk to the accumulator.
     * @param text The text chunk to append
     */
    public void appendContent(String text) {
        if (text != null) content.append(text);
    }

    public void setFinalMetadata(OllamaChatResponse metadata) {
        this.finalMetadata = metadata;
        String fullText = content.toString();
        this.correct = parseCorrect(fullText);
        this.cleanedAnswer = removeJsonBlock(fullText);
    }

    /**
     * Converts the accumulated content into an EvaluationResult.
     * Parses the text to determine if the answer is correct and cleans up the model answer.
     * @return The parsed EvaluationResult
     */
    private Boolean parseCorrect(String text) {
        Pattern pattern = Pattern.compile("\\{\\s*\"correct\"\\s*:\\s*(true|false)\\s*}");
        Matcher matcher = pattern.matcher(text);
        if (matcher.find()) {
            return Boolean.parseBoolean(matcher.group(1));
        }
        return null;
    }

    private String removeJsonBlock(String text) {
        return text
                .replaceAll("\\{\\s*\"correct\"\\s*:\\s*(true|false)\\s*}", "")
                .replaceAll("\n{3,}", "\n\n")
                .trim();
    }
}
